#!/usr/bin/env bash
# Terminal menu for selecting and controlling BMI30 split-system versions.

set -euo pipefail

SCRIPT_DIR="$(cd -- "$(dirname -- "$0")" && pwd)"
HOST_DIR="$SCRIPT_DIR/host"
ACTIVE_ENV="$HOST_DIR/bmi30_split_active_version.env"
CORE_SERVICE="${BMI30_CORE_SERVICE:-bmi30-core.service}"

pause_menu() {
    printf "\nНажмите Enter, чтобы вернуться в меню..."
    read -r _
}

load_active_env() {
    if [[ -f "$ACTIVE_ENV" ]]; then
        # shellcheck disable=SC1090
        . "$ACTIVE_ENV"
    fi

    : "${BMI30_CORE_PATH:=}"
    : "${BMI30_GUI_PATH:=host/BMI30.GUI.001.py}"
    : "${BMI30_PORTAL_PATH:=hotspot_info_server.py}"
    : "${BMI30_SERVICE_URL:=http://127.0.0.1:8765}"
    : "${BMI30_SPLIT_VERSION:=}"
    : "${BMI30_SPLIT_LABEL:=}"
    : "${BMI30_SPLIT_SELECTED_BY:=}"
    : "${BMI30_SPLIT_SELECTED_AT:=}"
}

split_core_files_oldest_first() {
    local path files=()

    for path in "$HOST_DIR"/BMI30.001.py "$HOST_DIR"/BMI30.001.py.*; do
        [[ -f "$path" ]] || continue
        files+=("$(basename "$path")")
    done

    [[ ${#files[@]} -gt 0 ]] || return 0
    printf '%s\n' "${files[@]}" | sort -V
}

promote_active_split_version() {
    local active_file=""
    local core_file
    local ordered=()

    if [[ "${BMI30_CORE_PATH:-}" == host/* ]]; then
        active_file="${BMI30_CORE_PATH#host/}"
    fi

    if [[ -z "$active_file" ]]; then
        return 0
    fi

    for core_file in "${SPLIT_CORE_FILES[@]}"; do
        if [[ "$core_file" == "$active_file" ]]; then
            ordered+=("$core_file")
            break
        fi
    done

    if [[ ${#ordered[@]} -eq 0 ]]; then
        return 0
    fi

    for core_file in "${SPLIT_CORE_FILES[@]}"; do
        [[ "$core_file" == "$active_file" ]] && continue
        ordered+=("$core_file")
    done

    SPLIT_CORE_FILES=("${ordered[@]}")
}

list_split_versions() {
    mapfile -t SPLIT_CORE_FILES < <(split_core_files_oldest_first)

    if [[ ${#SPLIT_CORE_FILES[@]} -eq 0 ]]; then
        echo "Нет версий split-системы host/BMI30.001.py*"
        exit 1
    fi

    mapfile -t SPLIT_CORE_FILES < <(printf '%s\n' "${SPLIT_CORE_FILES[@]}" | sort -Vr)
    promote_active_split_version
}

latest_split_core_file() {
    local files=()
    mapfile -t files < <(split_core_files_oldest_first)

    if [[ ${#files[@]} -eq 0 ]]; then
        echo "Нет версий split-системы host/BMI30.001.py*" >&2
        exit 1
    fi

    local last_index
    last_index=$((${#files[@]} - 1))
    printf '%s\n' "${files[$last_index]}"
}

split_version_from_core_file() {
    local core_file="$1"
    local date_part time_part core_path

    core_path="$HOST_DIR/$core_file"
    if [[ "$core_file" =~ ([0-9]{4}-[0-9]{2}-[0-9]{2}) ]]; then
        date_part="${BASH_REMATCH[1]}"
    elif [[ -f "$core_path" ]]; then
        date_part="$(date -r "$core_path" '+%Y-%m-%d')"
    else
        date_part="$(date '+%Y-%m-%d')"
    fi

    if [[ -f "$core_path" ]]; then
        time_part="$(date -r "$core_path" '+%H%M')"
    else
        time_part="$(date '+%H%M')"
    fi

    printf '%s-%s\n' "$date_part" "$time_part"
}

split_label_from_core_file() {
    local core_file="$1"
    local version date_part time_part

    version="$(split_version_from_core_file "$core_file")"
    if [[ "$version" =~ ^([0-9]{4}-[0-9]{2}-[0-9]{2})-([0-9]{2})([0-9]{2})$ ]]; then
        date_part="${BASH_REMATCH[1]}"
        time_part="${BASH_REMATCH[2]}:${BASH_REMATCH[3]}"
        printf '%s %s\n' "$date_part" "$time_part"
        return 0
    fi

    printf '%s\n' "$version"
}

save_active_split() {
    local core_file="$1"
    local selected_by="${2:-terminal-menu}"
    local version label selected_at

    version="$(split_version_from_core_file "$core_file")"
    label="$(split_label_from_core_file "$core_file")"
    selected_at="$(date -Iseconds)"

    load_active_env
    {
        printf '# Auto-generated by switch_bmi30_split_versions.sh\n'
        printf '# BMI30 split-system version selected from Terminal -> Run Task.\n'
        printf 'BMI30_SPLIT_VERSION=%q\n' "$version"
        printf 'BMI30_SPLIT_LABEL=%q\n' "$label"
        printf 'BMI30_SPLIT_SELECTED_BY=%q\n' "$selected_by"
        printf 'BMI30_SPLIT_SELECTED_AT=%q\n' "$selected_at"
        printf 'BMI30_CORE_PATH=%q\n' "host/$core_file"
        printf 'BMI30_GUI_PATH=%q\n' "$BMI30_GUI_PATH"
        printf 'BMI30_PORTAL_PATH=%q\n' "$BMI30_PORTAL_PATH"
        printf 'BMI30_SERVICE_URL=%q\n' "$BMI30_SERVICE_URL"
    } > "$ACTIVE_ENV"

    echo "Активная версия split-системы сохранена: $label"
    echo "Core: host/$core_file"
    echo "GUI:  $BMI30_GUI_PATH"
    echo "Web:  $BMI30_PORTAL_PATH"
}

ensure_latest_split_active() {
    local latest
    latest="$(latest_split_core_file)"

    load_active_env
    if [[ -z "$BMI30_CORE_PATH" || "$BMI30_CORE_PATH" == "host/BMI30.001.py" || ! -f "$SCRIPT_DIR/$BMI30_CORE_PATH" ]]; then
        save_active_split "$latest" "auto-latest"
    fi
}

core_service_state_text() {
    if ! command -v systemctl >/dev/null 2>&1; then
        printf "systemctl недоступен"
        return 0
    fi

    local state
    state="$(systemctl is-active "$CORE_SERVICE" 2>&1 || true)"
    case "$state" in
        *"Failed to connect"*|*"System has not been booted"*|*"Host is down"*)
            printf "systemd недоступен"
            ;;
        active)
            printf "запущено"
            ;;
        inactive)
            printf "остановлено"
            ;;
        activating)
            printf "запускается"
            ;;
        deactivating)
            printf "останавливается"
            ;;
        failed)
            printf "ошибка"
            ;;
        unknown|"")
            if systemctl cat "$CORE_SERVICE" >/dev/null 2>&1; then
                printf "неизвестно"
            else
                printf "сервис не найден"
            fi
            ;;
        *)
            printf "%s" "$state"
            ;;
    esac
}

core_service_enabled_text() {
    if ! command -v systemctl >/dev/null 2>&1; then
        return 0
    fi

    local enabled
    enabled="$(systemctl is-enabled "$CORE_SERVICE" 2>/dev/null || true)"
    case "$enabled" in
        enabled)
            printf "автозапуск включен"
            ;;
        disabled)
            printf "автозапуск выключен"
            ;;
        static|generated|indirect|alias)
            printf "%s" "$enabled"
            ;;
        ""|not-found|*"Failed to connect"*|*"System has not been booted"*|*"Host is down"*)
            ;;
        *)
            printf "%s" "$enabled"
            ;;
    esac
}

show_core_service_status() {
    local state_text enabled_text
    state_text="$(core_service_state_text)"
    enabled_text="$(core_service_enabled_text)"

    printf "BMI30 split-система: %s" "$state_text"
    if [[ -n "$enabled_text" ]]; then
        printf " / %s" "$enabled_text"
    fi
    printf " (%s)\n" "$CORE_SERVICE"
}

show_active_split_status() {
    local active latest latest_label active_label selected_by selected_at
    load_active_env
    latest="$(latest_split_core_file)"
    active="${BMI30_CORE_PATH:-не выбрано}"
    latest_label="$(split_label_from_core_file "$latest")"
    active_label="${BMI30_SPLIT_LABEL:-}"
    selected_by="${BMI30_SPLIT_SELECTED_BY:-unknown}"
    selected_at="${BMI30_SPLIT_SELECTED_AT:-unknown}"

    if [[ -z "$active_label" && "$active" == host/* ]]; then
        active_label="$(split_label_from_core_file "${active#host/}")"
    fi

    printf "Активная split-версия: %s\n" "${active_label:-$active}"
    printf "Core файл: %s\n" "$active"
    printf "Последняя split-версия: %s (host/%s)\n" "$latest_label" "$latest"
    printf "Источник выбора: %s / %s\n" "$selected_by" "$selected_at"
}

run_core_service_action() {
    local action="$1"
    local title="$2"

    printf "\n=== %s ===\n\n" "$title"
    if sudo systemctl "$action" "$CORE_SERVICE"; then
        echo "Готово."
    else
        local status=$?
        echo "Команда завершилась с кодом $status."
    fi

    printf "\n"
    show_core_service_status
}

activate_split_and_restart() {
    local core_file="$1"

    save_active_split "$core_file"
    run_core_service_action restart "Перезапуск BMI30 split-системы"
}

show_core_service_details() {
    printf "\n"
    show_active_split_status
    show_core_service_status
    printf "\n"

    if command -v systemctl >/dev/null 2>&1; then
        systemctl --no-pager --full status "$CORE_SERVICE" || true
    fi
}

split_label_suffix() {
    local core_file="$1"
    local latest="$2"
    local suffix=""

    if [[ "host/$core_file" == "$BMI30_CORE_PATH" ]]; then
        suffix+="  [active]"
    fi

    if [[ "$core_file" == "$latest" ]]; then
        suffix+="  [latest/autostart]"
    fi

    printf '%s' "$suffix"
}

ensure_latest_split_active

while true; do
    load_active_env
    list_split_versions

    latest="$(latest_split_core_file)"
    start_opt=$((${#SPLIT_CORE_FILES[@]} + 1))
    stop_opt=$((${#SPLIT_CORE_FILES[@]} + 2))
    restart_opt=$((${#SPLIT_CORE_FILES[@]} + 3))
    latest_opt=$((${#SPLIT_CORE_FILES[@]} + 4))
    status_opt=$((${#SPLIT_CORE_FILES[@]} + 5))

    printf "\n==========================================\n"
    printf "   BMI30 split-system versions\n"
    printf "==========================================\n"
    show_active_split_status
    show_core_service_status
    printf "\n"

    for i in "${!SPLIT_CORE_FILES[@]}"; do
        n=$((i + 1))
        label="$(split_label_from_core_file "${SPLIT_CORE_FILES[$i]}")"
        printf '%d) %s  (%s)%s\n' "$n" "$label" "${SPLIT_CORE_FILES[$i]}" "$(split_label_suffix "${SPLIT_CORE_FILES[$i]}" "$latest")"
    done

    printf '%d) Запустить активную split-систему BMI30\n' "$start_opt"
    printf '%d) Остановить работающую split-систему BMI30\n' "$stop_opt"
    printf '%d) Перезапустить активную split-систему BMI30\n' "$restart_opt"
    printf '%d) Сделать последнюю split-версию активной и запустить\n' "$latest_opt"
    printf '%d) Показать подробный статус split-системы BMI30\n' "$status_opt"
    printf "0) Exit\n"
    printf "\nВведите номер: "
    read -r choice

    if [[ "$choice" == "0" ]]; then
        echo "Выход."
        exit 0
    fi

    if ! [[ "$choice" =~ ^[0-9]+$ ]]; then
        echo "Неверный выбор"
        pause_menu
        continue
    fi

    if (( choice >= 1 && choice <= ${#SPLIT_CORE_FILES[@]} )); then
        idx=$((choice - 1))
        activate_split_and_restart "${SPLIT_CORE_FILES[$idx]}"
        pause_menu
    elif (( choice == start_opt )); then
        run_core_service_action start "Запуск BMI30 split-системы"
        pause_menu
    elif (( choice == stop_opt )); then
        run_core_service_action stop "Остановка BMI30 split-системы"
        pause_menu
    elif (( choice == restart_opt )); then
        run_core_service_action restart "Перезапуск BMI30 split-системы"
        pause_menu
    elif (( choice == latest_opt )); then
        activate_split_and_restart "$latest"
        pause_menu
    elif (( choice == status_opt )); then
        show_core_service_details
        pause_menu
    else
        echo "Неверный выбор"
        pause_menu
    fi
done
