#!/usr/bin/env bash
# Terminal menu for selecting and controlling split BMI30 core versions.

set -euo pipefail

SCRIPT_DIR="$(cd -- "$(dirname -- "$0")" && pwd)"
HOST_DIR="$SCRIPT_DIR/host"
ACTIVE_ENV="$HOST_DIR/bmi30_split_active_version.env"
CORE_SERVICE="${BMI30_CORE_SERVICE:-bmi30-core.service}"

pause_menu() {
    printf "\nНажмите Enter, чтобы вернуться в меню..."
    read -r _
}

load_active_env() {
    if [[ -f "$ACTIVE_ENV" ]]; then
        # shellcheck disable=SC1090
        . "$ACTIVE_ENV"
    fi

    : "${BMI30_CORE_PATH:=}"
    : "${BMI30_GUI_PATH:=host/BMI30.GUI.001.py}"
    : "${BMI30_SERVICE_URL:=http://127.0.0.1:8765}"
}

list_core_versions() {
    CORE_FILES=()

    local path
    for path in "$HOST_DIR"/BMI30.001.py "$HOST_DIR"/BMI30.001.py.*; do
        [[ -f "$path" ]] || continue
        CORE_FILES+=("$(basename "$path")")
    done

    if [[ ${#CORE_FILES[@]} -eq 0 ]]; then
        echo "Нет версий ядра host/BMI30.001.py*"
        exit 1
    fi

    mapfile -t CORE_FILES < <(printf '%s\n' "${CORE_FILES[@]}" | sort -V)
}

latest_core_file() {
    list_core_versions
    local last_index
    last_index=$((${#CORE_FILES[@]} - 1))
    printf '%s\n' "${CORE_FILES[$last_index]}"
}

save_active_core() {
    local core_file="$1"

    load_active_env
    {
        printf '# Auto-generated by switch_bmi30_core_versions.sh\n'
        printf '# Core service version is selected from Terminal -> Run Task.\n'
        printf 'BMI30_CORE_PATH=%q\n' "host/$core_file"
        printf 'BMI30_GUI_PATH=%q\n' "$BMI30_GUI_PATH"
        printf 'BMI30_SERVICE_URL=%q\n' "$BMI30_SERVICE_URL"
    } > "$ACTIVE_ENV"

    echo "Активная версия ядра сохранена: host/$core_file"
}

ensure_latest_core_active() {
    local latest
    latest="$(latest_core_file)"

    load_active_env
    if [[ -z "$BMI30_CORE_PATH" || "$BMI30_CORE_PATH" == "host/BMI30.001.py" || ! -f "$SCRIPT_DIR/$BMI30_CORE_PATH" ]]; then
        save_active_core "$latest"
    fi
}

core_service_state_text() {
    if ! command -v systemctl >/dev/null 2>&1; then
        printf "systemctl недоступен"
        return 0
    fi

    local state
    state="$(systemctl is-active "$CORE_SERVICE" 2>&1 || true)"
    case "$state" in
        *"Failed to connect"*|*"System has not been booted"*|*"Host is down"*)
            printf "systemd недоступен"
            ;;
        active)
            printf "запущено"
            ;;
        inactive)
            printf "остановлено"
            ;;
        activating)
            printf "запускается"
            ;;
        deactivating)
            printf "останавливается"
            ;;
        failed)
            printf "ошибка"
            ;;
        unknown|"")
            if systemctl cat "$CORE_SERVICE" >/dev/null 2>&1; then
                printf "неизвестно"
            else
                printf "сервис не найден"
            fi
            ;;
        *)
            printf "%s" "$state"
            ;;
    esac
}

core_service_enabled_text() {
    if ! command -v systemctl >/dev/null 2>&1; then
        return 0
    fi

    local enabled
    enabled="$(systemctl is-enabled "$CORE_SERVICE" 2>/dev/null || true)"
    case "$enabled" in
        enabled)
            printf "автозапуск включен"
            ;;
        disabled)
            printf "автозапуск выключен"
            ;;
        static|generated|indirect|alias)
            printf "%s" "$enabled"
            ;;
        ""|not-found|*"Failed to connect"*|*"System has not been booted"*|*"Host is down"*)
            ;;
        *)
            printf "%s" "$enabled"
            ;;
    esac
}

show_core_service_status() {
    local state_text enabled_text
    state_text="$(core_service_state_text)"
    enabled_text="$(core_service_enabled_text)"

    printf "Автономное ядро BMI30: %s" "$state_text"
    if [[ -n "$enabled_text" ]]; then
        printf " / %s" "$enabled_text"
    fi
    printf " (%s)\n" "$CORE_SERVICE"
}

show_active_core_status() {
    local active latest
    load_active_env
    latest="$(latest_core_file)"
    active="${BMI30_CORE_PATH:-не выбрано}"

    printf "Активная версия ядра: %s\n" "$active"
    printf "Последняя версия ядра: host/%s\n" "$latest"
}

run_core_service_action() {
    local action="$1"
    local title="$2"

    printf "\n=== %s ===\n\n" "$title"
    if sudo systemctl "$action" "$CORE_SERVICE"; then
        echo "Готово."
    else
        local status=$?
        echo "Команда завершилась с кодом $status."
    fi

    printf "\n"
    show_core_service_status
}

activate_core_and_restart() {
    local core_file="$1"

    save_active_core "$core_file"
    run_core_service_action restart "Перезапуск автономного ядра BMI30"
}

show_core_service_details() {
    printf "\n"
    show_active_core_status
    show_core_service_status
    printf "\n"

    if command -v systemctl >/dev/null 2>&1; then
        systemctl --no-pager --full status "$CORE_SERVICE" || true
    fi
}

core_label_suffix() {
    local core_file="$1"
    local latest="$2"
    local suffix=""

    if [[ "$core_file" == "BMI30.001.py.2026-06-17-yesterday" ]]; then
        suffix+="  [вчерашнее]"
    elif [[ "$core_file" == "BMI30.001.py.2026-06-18-today" ]]; then
        suffix+="  [сегодняшнее]"
    fi

    if [[ "host/$core_file" == "$BMI30_CORE_PATH" ]]; then
        suffix+="  [active]"
    fi

    if [[ "$core_file" == "$latest" ]]; then
        suffix+="  [latest/autostart]"
    fi

    printf '%s' "$suffix"
}

ensure_latest_core_active

while true; do
    load_active_env
    list_core_versions

    latest="$(latest_core_file)"
    start_opt=$((${#CORE_FILES[@]} + 1))
    stop_opt=$((${#CORE_FILES[@]} + 2))
    restart_opt=$((${#CORE_FILES[@]} + 3))
    latest_opt=$((${#CORE_FILES[@]} + 4))
    status_opt=$((${#CORE_FILES[@]} + 5))

    printf "\n==========================================\n"
    printf "   BMI30 core versions\n"
    printf "==========================================\n"
    show_active_core_status
    show_core_service_status
    printf "\n"

    for i in "${!CORE_FILES[@]}"; do
        n=$((i + 1))
        printf '%d) %s%s\n' "$n" "${CORE_FILES[$i]}" "$(core_label_suffix "${CORE_FILES[$i]}" "$latest")"
    done

    printf '%d) Запустить активное ядро BMI30\n' "$start_opt"
    printf '%d) Остановить работающее ядро BMI30\n' "$stop_opt"
    printf '%d) Перезапустить активное ядро BMI30\n' "$restart_opt"
    printf '%d) Сделать последнюю версию активной и запустить\n' "$latest_opt"
    printf '%d) Показать подробный статус ядра BMI30\n' "$status_opt"
    printf "0) Exit\n"
    printf "\nВведите номер: "
    read -r choice

    if [[ "$choice" == "0" ]]; then
        echo "Выход."
        exit 0
    fi

    if ! [[ "$choice" =~ ^[0-9]+$ ]]; then
        echo "Неверный выбор"
        pause_menu
        continue
    fi

    if (( choice >= 1 && choice <= ${#CORE_FILES[@]} )); then
        idx=$((choice - 1))
        activate_core_and_restart "${CORE_FILES[$idx]}"
        pause_menu
    elif (( choice == start_opt )); then
        run_core_service_action start "Запуск автономного ядра BMI30"
        pause_menu
    elif (( choice == stop_opt )); then
        run_core_service_action stop "Остановка автономного ядра BMI30"
        pause_menu
    elif (( choice == restart_opt )); then
        run_core_service_action restart "Перезапуск автономного ядра BMI30"
        pause_menu
    elif (( choice == latest_opt )); then
        activate_core_and_restart "$latest"
        pause_menu
    elif (( choice == status_opt )); then
        show_core_service_details
        pause_menu
    else
        echo "Неверный выбор"
        pause_menu
    fi
done
