#!/bin/bash
# Скрипт для быстрого переключения между версиями BMI30.200.py

SCRIPT_DIR="$(cd -- "$(dirname -- "$0")" && pwd)"
HOST_DIR="$SCRIPT_DIR/host"
ACTIVE_VERSION_ENV="$HOST_DIR/bmi30_active_version.env"

resolve_python() {
    if [[ -x "$SCRIPT_DIR/.usbvenv/bin/python" ]]; then
        printf '%s\n' "$SCRIPT_DIR/.usbvenv/bin/python"
        return 0
    fi

    if [[ -x "$SCRIPT_DIR/.venv/bin/python" ]]; then
        printf '%s\n' "$SCRIPT_DIR/.venv/bin/python"
        return 0
    fi

    if command -v python3 >/dev/null 2>&1; then
        command -v python3
        return 0
    fi

    return 1
}

PYTHON_BIN="$(resolve_python || true)"

run_version() {
    local version_file="$1"
    local app_path="host/$version_file"

    if [[ -z "$PYTHON_BIN" ]]; then
        echo "Ошибка: не найден Python в .usbvenv/bin/python, .venv/bin/python или системный python3"
        exit 1
    fi

    if [[ ! -f "$HOST_DIR/$version_file" ]]; then
        echo "Ошибка: не найден файл версии $HOST_DIR/$version_file"
        exit 1
    fi

    {
        printf '# Auto-generated by switch_version.sh. This is the current BMI30 app file for launch and edits.\n'
        printf 'BMI30_APP_PATH=%q\n' "$app_path"
    } > "$ACTIVE_VERSION_ENV"
    echo "Активная версия сохранена: $app_path"

    pkill -f BMI30.200.py
    sleep 0.5
    cd "$SCRIPT_DIR" || exit 1
    : "${BMI30_BEEP_REALTIME:=1}"
    : "${BMI30_DETECT_IN_READER:=1}"
    : "${BMI30_BEEP_HOLD_ENABLE:=0}"
    : "${BMI30_BEEP_HOLD_DELAY:=0.0}"
    : "${BMI30_DETECT_LOSS_SEC:=0.0}"
    : "${BMI30_DETECT_COOLDOWN:=0.05}"
    : "${BMI30_BEEP_SWEEP:=0}"
    : "${BMI30_BEEP_INFO_TONE:=0.150}"
    : "${BMI30_BEEP_INFO_GAP:=0.0}"
    : "${BMI30_BEEP_CHANNEL_GAP:=0.0}"
    : "${BMI30_BEEP_REPEAT_GAP:=0.05}"
    : "${BMI30_RESET_ON_START:=1}"
    : "${BMI30_STARTUP_RESET_MODE:=fast_gpio}"
    : "${BMI30_STARTUP_RESET_PULSE_MS:=120}"
    : "${BMI30_STARTUP_RESET_WAIT_S:=0.0}"
    : "${BMI30_STARTUP_READY_TIMEOUT_S:=3.0}"
    : "${BMI30_STARTUP_READY_POLL_S:=0.05}"
    : "${BMI30_CONNECT_TIMEOUT_S:=4.0}"
    : "${BMI30_DEFAULT_SEL:=5}"
    : "${BMI30_HOST_RX_ACK:=1}"
    : "${BMI30_HOST_RX_ACK_INTERVAL:=1.0}"
    export BMI30_BEEP_REALTIME BMI30_DETECT_IN_READER BMI30_BEEP_HOLD_ENABLE BMI30_BEEP_HOLD_DELAY
    export BMI30_DETECT_LOSS_SEC BMI30_DETECT_COOLDOWN BMI30_BEEP_SWEEP
    export BMI30_BEEP_INFO_TONE BMI30_BEEP_INFO_GAP BMI30_BEEP_CHANNEL_GAP BMI30_BEEP_REPEAT_GAP
    export BMI30_RESET_ON_START BMI30_STARTUP_RESET_MODE BMI30_STARTUP_RESET_PULSE_MS BMI30_STARTUP_RESET_WAIT_S
    export BMI30_STARTUP_READY_TIMEOUT_S BMI30_STARTUP_READY_POLL_S BMI30_CONNECT_TIMEOUT_S BMI30_DEFAULT_SEL
    export BMI30_HOST_RX_ACK BMI30_HOST_RX_ACK_INTERVAL
    exec "$PYTHON_BIN" "$HOST_DIR/$version_file"
}

# Очистка буфера ввода
while read -t 0; do read -n 1; done

echo "=========================================="
echo "   Переключение версий BMI30.200.py"
echo "=========================================="
echo ""

PS3="Введите номер (или 0 для выхода): "
options=(
    "РАБОЧАЯ - 2026-06-08 realtime-prevbuf - копия текущего первого пункта для правок"
    "РАБОЧАЯ - 2026-06-03 realtime-prevbuf - предыдущая рабочая версия"
    "РАБОЧАЯ - 2026-05-30 realtime-prevbuf - предыдущая рабочая версия"
    "РАБОЧАЯ - 2026-05-26 realtime-prevbuf - предыдущая рабочая версия"
    "РАБОЧАЯ - 2026-05-25 realtime-prevbuf - предыдущая копия для правок"
    "БАЗОВАЯ - 2026-05-25 realtime-prevbuf - сохраненная база перед следующими правками"
    "РАБОЧАЯ - 2026-05-24 + AUTORESET - предыдущая основная версия"
    "2026-04-06 + AUTORESET - исходная рабочая стабильная база"
    "2026-02-07 + AUTORESET - Стабильная рабочая база"
    "2026-02-07 (29d4cb5) - Update UI and PWM controls"
    "2026-02-11 (35e2110) - ROI: обновление start/len"
    "2026-02-12 (5f33318) - Настроить смещение метки Б"
    "2026-02-15 (b2aba85) - Стабилизация детекции"
    "2026-02-16 - С оптимизированными фильтрами (быстрые avg7/9/11)"
    "DEV - BMI30.200.py (текущий host/BMI30.200.py)"
    "Выход"
)

select opt in "${options[@]}"; do
    case $REPLY in
        1)
            echo "Запускаю РАБОЧУЮ версию 2026-06-08 realtime-prevbuf (копия текущего первого пункта для правок)..."
            run_version "BMI30.200.py.2026-06-08-realtime-prevbuf"
            break
            ;;
        2)
            echo "Запускаю предыдущую РАБОЧУЮ версию 2026-06-03 realtime-prevbuf..."
            run_version "BMI30.200.py.2026-06-03-realtime-prevbuf"
            break
            ;;
        3)
            echo "Запускаю предыдущую РАБОЧУЮ версию 2026-05-30 realtime-prevbuf..."
            run_version "BMI30.200.py.2026-05-30-realtime-prevbuf"
            break
            ;;
        4)
            echo "Запускаю предыдущую РАБОЧУЮ версию 2026-05-26 realtime-prevbuf..."
            run_version "BMI30.200.py.2026-05-26-realtime-prevbuf"
            break
            ;;
        5)
            echo "Запускаю предыдущую РАБОЧУЮ версию 2026-05-25 realtime-prevbuf..."
            run_version "BMI30.200.py.2026-05-25-realtime-prevbuf"
            break
            ;;
        6)
            echo "Запускаю БАЗОВУЮ сохраненную версию 2026-05-25 realtime-prevbuf..."
            run_version "BMI30.200.py.2026-05-25-realtime-prevbuf-base"
            break
            ;;
        7)
            echo "Запускаю предыдущую рабочую версию 2026-05-24 + AUTORESET..."
            run_version "BMI30.200.py.2026-05-24-work"
            break
            ;;
        8)
            echo "Запускаю исходную рабочую версию 2026-04-06 + AUTORESET..."
            run_version "BMI30.200.py.2026-04-06-autoreset"
            break
            ;;
        9)
            echo "Запускаю версию 2026-02-07 + AUTORESET..."
            run_version "BMI30.200.py.2026-02-07-autoreset"
            break
            ;;
        10)
            echo "Запускаю версию от 2026-02-07..."
            run_version "BMI30.200.py.2026-02-07"
            break
            ;;
        11)
            echo "Запускаю версию от 2026-02-11..."
            run_version "BMI30.200.py.old"
            break
            ;;
        12)
            echo "Запускаю версию от 2026-02-12..."
            run_version "BMI30.200.py.2026-02-12"
            break
            ;;
        13)
            echo "Запускаю версию от 2026-02-15..."
            run_version "BMI30.200.py.2026-02-15"
            break
            ;;
        14)
            echo "Запускаю версию от 2026-02-16 (с оптимизированными фильтрами)..."
            run_version "BMI30.200.py.2026-02-16"
            break
            ;;
        15)
            echo "Запускаю DEV-версию..."
            run_version "BMI30.200.py"
            break
            ;;
        16|0)
            echo "Выход."
            exit 0
            ;;
        *)
            echo "Неверный выбор! Попробуйте снова."
            ;;
    esac
done
