#!/bin/bash
# Debug launcher for split BMI30 GUI versions.

set -e

SCRIPT_DIR="$(cd -- "$(dirname -- "$0")" && pwd)"
HOST_DIR="$SCRIPT_DIR/host"
ACTIVE_ENV="$HOST_DIR/bmi30_split_active_version.env"
CORE_SERVICE="${BMI30_CORE_SERVICE:-bmi30-core.service}"

pause_menu() {
    echo ""
    read -r -p "Нажмите Enter, чтобы вернуться в меню..." _
}

resolve_python() {
    if [[ -x "$SCRIPT_DIR/.usbvenv/bin/python" ]]; then
        printf '%s\n' "$SCRIPT_DIR/.usbvenv/bin/python"
        return 0
    fi
    if [[ -x "$SCRIPT_DIR/.venv/bin/python" ]]; then
        printf '%s\n' "$SCRIPT_DIR/.venv/bin/python"
        return 0
    fi
    if command -v python3 >/dev/null 2>&1; then
        command -v python3
        return 0
    fi
    return 1
}

PYTHON_BIN="$(resolve_python || true)"
if [[ -z "$PYTHON_BIN" ]]; then
    echo "Ошибка: Python не найден"
    exit 1
fi

load_active_env() {
    if [[ -f "$ACTIVE_ENV" ]]; then
        # shellcheck disable=SC1090
        . "$ACTIVE_ENV"
    fi
    : "${BMI30_CORE_PATH:=host/BMI30.001.py}"
    : "${BMI30_GUI_PATH:=host/BMI30.GUI.001.py}"
    : "${BMI30_PORTAL_PATH:=hotspot_info_server.py}"
    : "${BMI30_SERVICE_URL:=http://127.0.0.1:8765}"
    : "${BMI30_SPLIT_VERSION:=}"
    : "${BMI30_SPLIT_LABEL:=}"
    : "${BMI30_SPLIT_SELECTED_BY:=}"
    : "${BMI30_SPLIT_SELECTED_AT:=}"
}

save_active_gui() {
    local gui_file="$1"
    load_active_env
    {
        printf '# Auto-generated by switch_bmi30_versions.sh\n'
        printf '# BMI30 split-system version is selected from Terminal -> Run Task.\n'
        if [[ -n "$BMI30_SPLIT_VERSION" ]]; then
            printf 'BMI30_SPLIT_VERSION=%q\n' "$BMI30_SPLIT_VERSION"
        fi
        if [[ -n "$BMI30_SPLIT_LABEL" ]]; then
            printf 'BMI30_SPLIT_LABEL=%q\n' "$BMI30_SPLIT_LABEL"
        fi
        if [[ -n "$BMI30_SPLIT_SELECTED_BY" ]]; then
            printf 'BMI30_SPLIT_SELECTED_BY=%q\n' "$BMI30_SPLIT_SELECTED_BY"
        fi
        if [[ -n "$BMI30_SPLIT_SELECTED_AT" ]]; then
            printf 'BMI30_SPLIT_SELECTED_AT=%q\n' "$BMI30_SPLIT_SELECTED_AT"
        fi
        printf 'BMI30_CORE_PATH=%q\n' "$BMI30_CORE_PATH"
        printf 'BMI30_GUI_PATH=%q\n' "host/$gui_file"
        printf 'BMI30_PORTAL_PATH=%q\n' "$BMI30_PORTAL_PATH"
        printf 'BMI30_SERVICE_URL=%q\n' "$BMI30_SERVICE_URL"
    } > "$ACTIVE_ENV"
    echo "Активная GUI версия сохранена: host/$gui_file"
    echo "Core service не менялся: $BMI30_CORE_PATH"
    echo "Версию split-системы можно выбрать через задачу: Выбор версий BMI30 split-системы"
}

core_service_state_text() {
    if ! command -v systemctl >/dev/null 2>&1; then
        printf "systemctl недоступен"
        return 0
    fi

    local state
    state="$(systemctl is-active "$CORE_SERVICE" 2>&1 || true)"
    case "$state" in
        *"Failed to connect"*|*"System has not been booted"*|*"Host is down"*)
            printf "systemd недоступен"
            ;;
        active)
            printf "запущено"
            ;;
        inactive)
            printf "остановлено"
            ;;
        activating)
            printf "запускается"
            ;;
        deactivating)
            printf "останавливается"
            ;;
        failed)
            printf "ошибка"
            ;;
        unknown|"")
            if systemctl cat "$CORE_SERVICE" >/dev/null 2>&1; then
                printf "неизвестно"
            else
                printf "сервис не найден"
            fi
            ;;
        *)
            printf "%s" "$state"
            ;;
    esac
}

core_service_enabled_text() {
    if ! command -v systemctl >/dev/null 2>&1; then
        return 0
    fi

    local enabled
    enabled="$(systemctl is-enabled "$CORE_SERVICE" 2>/dev/null || true)"
    case "$enabled" in
        enabled)
            printf "автозапуск включен"
            ;;
        disabled)
            printf "автозапуск выключен"
            ;;
        static|generated|indirect|alias)
            printf "%s" "$enabled"
            ;;
        ""|not-found|*"Failed to connect"*|*"System has not been booted"*|*"Host is down"*)
            ;;
        *)
            printf "%s" "$enabled"
            ;;
    esac
}

show_core_service_status() {
    local state_text enabled_text
    state_text="$(core_service_state_text)"
    enabled_text="$(core_service_enabled_text)"

    printf "BMI30 split-система: %s" "$state_text"
    if [[ -n "$enabled_text" ]]; then
        printf " / %s" "$enabled_text"
    fi
    printf " (%s)\n" "$CORE_SERVICE"
}

run_core_service_action() {
    local action="$1"
    local title="$2"

    echo ""
    echo "=== $title ==="
    echo ""
    if sudo systemctl "$action" "$CORE_SERVICE"; then
        echo "Готово."
    else
        local status=$?
        echo "Команда завершилась с кодом $status."
    fi
    echo ""
    show_core_service_status
}

show_core_service_details() {
    echo ""
    show_core_service_status
    echo ""
    if command -v systemctl >/dev/null 2>&1; then
        systemctl --no-pager --full status "$CORE_SERVICE" || true
    fi
}

list_gui_versions() {
    GUI_FILES=()
    local path
    for path in "$HOST_DIR"/BMI30.GUI.[0-9][0-9][0-9].py; do
        [[ -f "$path" ]] || continue
        GUI_FILES+=("$(basename "$path")")
    done
    if [[ ${#GUI_FILES[@]} -eq 0 ]]; then
        echo "Нет GUI версий host/BMI30.GUI.xxx.py"
        exit 1
    fi
}

start_gui() {
    local gui_file="$1"
    [[ -f "$HOST_DIR/$gui_file" ]] || { echo "Нет GUI: $HOST_DIR/$gui_file"; exit 1; }
    save_active_gui "$gui_file"
    cd "$SCRIPT_DIR"
    export BMI30_SERVICE_URL
    exec "$PYTHON_BIN" "$HOST_DIR/$gui_file"
}

load_active_env

while true; do
    load_active_env
    list_gui_versions

    start_opt=$((${#GUI_FILES[@]} + 1))
    stop_opt=$((${#GUI_FILES[@]} + 2))
    restart_opt=$((${#GUI_FILES[@]} + 3))
    status_opt=$((${#GUI_FILES[@]} + 4))

    echo "=========================================="
    echo "   BMI30 GUI versions"
    echo "=========================================="
    show_core_service_status
    echo "Split-system version is selected in the Terminal -> Run Task split menu."
    echo ""
    for i in "${!GUI_FILES[@]}"; do
        n=$((i + 1))
        marker=""
        if [[ "host/${GUI_FILES[$i]}" == "$BMI30_GUI_PATH" ]]; then
            marker="  [active]"
        fi
        printf '%d) %s%s\n' "$n" "${GUI_FILES[$i]}" "$marker"
    done
    printf '%d) Запустить BMI30 split-систему\n' "$start_opt"
    printf '%d) Остановить BMI30 split-систему\n' "$stop_opt"
    printf '%d) Перезапустить BMI30 split-систему\n' "$restart_opt"
    printf '%d) Показать подробный статус BMI30 split-системы\n' "$status_opt"
    echo "0) Exit"
    echo ""
    read -r -p "Введите номер: " choice

    if [[ "$choice" == "0" ]]; then
        echo "Выход."
        exit 0
    fi
    if ! [[ "$choice" =~ ^[0-9]+$ ]]; then
        echo "Неверный выбор"
        pause_menu
        continue
    fi

    if (( choice >= 1 && choice <= ${#GUI_FILES[@]} )); then
        idx=$((choice - 1))
        start_gui "${GUI_FILES[$idx]}"
    elif (( choice == start_opt )); then
        run_core_service_action start "Запуск BMI30 split-системы"
        pause_menu
    elif (( choice == stop_opt )); then
        run_core_service_action stop "Остановка BMI30 split-системы"
        pause_menu
    elif (( choice == restart_opt )); then
        run_core_service_action restart "Перезапуск BMI30 split-системы"
        pause_menu
    elif (( choice == status_opt )); then
        show_core_service_details
        pause_menu
    else
        echo "Неверный выбор"
        pause_menu
    fi
done
