#!/bin/bash
# Version menu for split BMI30 core service and remote GUI.

set -e

SCRIPT_DIR="$(cd -- "$(dirname -- "$0")" && pwd)"
HOST_DIR="$SCRIPT_DIR/host"
ACTIVE_ENV="$HOST_DIR/bmi30_split_active_version.env"

resolve_python() {
    if [[ -x "$SCRIPT_DIR/.usbvenv/bin/python" ]]; then
        printf '%s\n' "$SCRIPT_DIR/.usbvenv/bin/python"
        return 0
    fi
    if [[ -x "$SCRIPT_DIR/.venv/bin/python" ]]; then
        printf '%s\n' "$SCRIPT_DIR/.venv/bin/python"
        return 0
    fi
    if command -v python3 >/dev/null 2>&1; then
        command -v python3
        return 0
    fi
    return 1
}

PYTHON_BIN="$(resolve_python || true)"
if [[ -z "$PYTHON_BIN" ]]; then
    echo "Ошибка: Python не найден"
    exit 1
fi

CORE_VERSION="BMI30.001.py"
GUI_VERSION="BMI30.GUI.001.py"

save_active() {
    {
        printf '# Auto-generated by switch_bmi30_versions.sh\n'
        printf 'BMI30_CORE_PATH=%q\n' "host/$CORE_VERSION"
        printf 'BMI30_GUI_PATH=%q\n' "host/$GUI_VERSION"
        printf 'BMI30_SERVICE_URL=%q\n' "${BMI30_SERVICE_URL:-http://127.0.0.1:8765}"
    } > "$ACTIVE_ENV"
    echo "Активные версии сохранены:"
    echo "  core: host/$CORE_VERSION"
    echo "  gui : host/$GUI_VERSION"
}

check_files() {
    [[ -f "$HOST_DIR/$CORE_VERSION" ]] || { echo "Нет core: $HOST_DIR/$CORE_VERSION"; exit 1; }
    [[ -f "$HOST_DIR/$GUI_VERSION" ]] || { echo "Нет GUI: $HOST_DIR/$GUI_VERSION"; exit 1; }
}

start_core() {
    check_files
    save_active
    cd "$SCRIPT_DIR"
    exec "$PYTHON_BIN" "$HOST_DIR/$CORE_VERSION"
}

start_gui() {
    check_files
    save_active
    cd "$SCRIPT_DIR"
    exec "$PYTHON_BIN" "$HOST_DIR/$GUI_VERSION"
}

start_both() {
    check_files
    save_active
    cd "$SCRIPT_DIR"
    if ! "$PYTHON_BIN" - <<'PY'
from urllib.request import urlopen
try:
    urlopen("http://127.0.0.1:8765/health", timeout=0.3).read()
    raise SystemExit(0)
except Exception:
    raise SystemExit(1)
PY
    then
        echo "Core service не отвечает, запускаю в фоне..."
        "$PYTHON_BIN" "$HOST_DIR/$CORE_VERSION" &
        sleep 1
    fi
    exec "$PYTHON_BIN" "$HOST_DIR/$GUI_VERSION"
}

echo "=========================================="
echo "   BMI30 split versions"
echo "=========================================="
echo "1) Core service: $CORE_VERSION"
echo "2) GUI client  : $GUI_VERSION"
echo "3) Core + GUI  : $CORE_VERSION + $GUI_VERSION"
echo "4) Save active versions only"
echo "0) Exit"
echo ""
read -r -p "Введите номер: " choice

case "$choice" in
    1) start_core ;;
    2) start_gui ;;
    3) start_both ;;
    4) check_files; save_active ;;
    0) echo "Выход." ;;
    *) echo "Неверный выбор"; exit 1 ;;
esac
