#!/bin/bash
# Debug launcher for split BMI30 GUI versions.

set -e

SCRIPT_DIR="$(cd -- "$(dirname -- "$0")" && pwd)"
HOST_DIR="$SCRIPT_DIR/host"
ACTIVE_ENV="$HOST_DIR/bmi30_split_active_version.env"

resolve_python() {
    if [[ -x "$SCRIPT_DIR/.usbvenv/bin/python" ]]; then
        printf '%s\n' "$SCRIPT_DIR/.usbvenv/bin/python"
        return 0
    fi
    if [[ -x "$SCRIPT_DIR/.venv/bin/python" ]]; then
        printf '%s\n' "$SCRIPT_DIR/.venv/bin/python"
        return 0
    fi
    if command -v python3 >/dev/null 2>&1; then
        command -v python3
        return 0
    fi
    return 1
}

PYTHON_BIN="$(resolve_python || true)"
if [[ -z "$PYTHON_BIN" ]]; then
    echo "Ошибка: Python не найден"
    exit 1
fi

load_active_env() {
    if [[ -f "$ACTIVE_ENV" ]]; then
        # shellcheck disable=SC1090
        . "$ACTIVE_ENV"
    fi
    : "${BMI30_CORE_PATH:=host/BMI30.001.py}"
    : "${BMI30_GUI_PATH:=host/BMI30.GUI.001.py}"
    : "${BMI30_SERVICE_URL:=http://127.0.0.1:8765}"
}

save_active_gui() {
    local gui_file="$1"
    load_active_env
    {
        printf '# Auto-generated by switch_bmi30_versions.sh\n'
        printf '# Core service version is selected from the web portal.\n'
        printf 'BMI30_CORE_PATH=%q\n' "$BMI30_CORE_PATH"
        printf 'BMI30_GUI_PATH=%q\n' "host/$gui_file"
        printf 'BMI30_SERVICE_URL=%q\n' "$BMI30_SERVICE_URL"
    } > "$ACTIVE_ENV"
    echo "Активная GUI версия сохранена: host/$gui_file"
    echo "Core service не менялся: $BMI30_CORE_PATH"
}

list_gui_versions() {
    GUI_FILES=()
    local path
    for path in "$HOST_DIR"/BMI30.GUI.[0-9][0-9][0-9].py; do
        [[ -f "$path" ]] || continue
        GUI_FILES+=("$(basename "$path")")
    done
    if [[ ${#GUI_FILES[@]} -eq 0 ]]; then
        echo "Нет GUI версий host/BMI30.GUI.xxx.py"
        exit 1
    fi
}

start_gui() {
    local gui_file="$1"
    [[ -f "$HOST_DIR/$gui_file" ]] || { echo "Нет GUI: $HOST_DIR/$gui_file"; exit 1; }
    save_active_gui "$gui_file"
    cd "$SCRIPT_DIR"
    export BMI30_SERVICE_URL
    exec "$PYTHON_BIN" "$HOST_DIR/$gui_file"
}

load_active_env
list_gui_versions

echo "=========================================="
echo "   BMI30 GUI versions"
echo "=========================================="
echo "Core service always runs via systemd."
echo "Core service version is selected in the web portal."
echo ""
for i in "${!GUI_FILES[@]}"; do
    n=$((i + 1))
    marker=""
    if [[ "host/${GUI_FILES[$i]}" == "$BMI30_GUI_PATH" ]]; then
        marker="  [active]"
    fi
    printf '%d) %s%s\n' "$n" "${GUI_FILES[$i]}" "$marker"
done
echo "0) Exit"
echo ""
read -r -p "Введите номер: " choice

if [[ "$choice" == "0" ]]; then
    echo "Выход."
    exit 0
fi
if ! [[ "$choice" =~ ^[0-9]+$ ]]; then
    echo "Неверный выбор"
    exit 1
fi
idx=$((choice - 1))
if (( idx < 0 || idx >= ${#GUI_FILES[@]} )); then
    echo "Неверный выбор"
    exit 1
fi
start_gui "${GUI_FILES[$idx]}"
