#!/usr/bin/env bash
# Create an immutable, self-contained BMI30 websplit runtime bundle.

set -euo pipefail

SCRIPT_DIR="$(cd -- "$(dirname -- "$0")" && pwd)"
PROJECT_ROOT="$(cd -- "$SCRIPT_DIR/.." && pwd)"
BUNDLES_DIR="$PROJECT_ROOT/host/bmi30_split_bundles"

SOURCE_PROJECT="$PROJECT_ROOT"
SOURCE_SYSTEM_ROOT="/"
BUNDLE_ID=""
BUNDLE_LABEL=""
BUNDLE_ORIGIN="local-project"
INCLUDE_PLAYER=1
PORTAL_SOURCE=""

usage() {
    cat <<'EOF'
Использование:
  sudo ./utilities/create_bmi30_split_bundle.sh --id ID [параметры]

Параметры:
  --id ID                    Уникальный ID полного комплекта.
  --label TEXT               Подпись в меню (по умолчанию ID).
  --origin TEXT              Источник/примечание для manifest.
  --source-project PATH      Исходный каталог Documents.
  --source-system-root PATH  Корень системы-источника для BMI30-конфигов.
  --portal-source PATH       Явно взять portal из указанного project/absolute пути.
  --without-player           Не включать host/player_recordings.

Скрипт читает host/bmi30_split_active_version.env источника и сохраняет:
core, engine, GUI, portal, project/system BMI30 config, bmi30_sel,
DC calibration, tag_response_filters, usb_vendor и (по умолчанию) player recordings.
EOF
}

die() {
    printf '[ERR] %s\n' "$*" >&2
    exit 1
}

info() {
    printf '[INFO] %s\n' "$*"
}

parse_args() {
    while [[ $# -gt 0 ]]; do
        case "$1" in
            --id)
                [[ $# -ge 2 ]] || die "После --id нужен ID"
                BUNDLE_ID="$2"
                shift 2
                ;;
            --label)
                [[ $# -ge 2 ]] || die "После --label нужна подпись"
                BUNDLE_LABEL="$2"
                shift 2
                ;;
            --origin)
                [[ $# -ge 2 ]] || die "После --origin нужен текст"
                BUNDLE_ORIGIN="$2"
                shift 2
                ;;
            --source-project)
                [[ $# -ge 2 ]] || die "После --source-project нужен путь"
                SOURCE_PROJECT="$2"
                shift 2
                ;;
            --source-system-root)
                [[ $# -ge 2 ]] || die "После --source-system-root нужен путь"
                SOURCE_SYSTEM_ROOT="$2"
                shift 2
                ;;
            --portal-source)
                [[ $# -ge 2 ]] || die "После --portal-source нужен PATH"
                PORTAL_SOURCE="$2"
                shift 2
                ;;
            --without-player)
                INCLUDE_PLAYER=0
                shift
                ;;
            --help|-h)
                usage
                exit 0
                ;;
            *)
                die "Неизвестный параметр: $1"
                ;;
        esac
    done
}

resolve_project_file() {
    local rel="$1"
    [[ -n "$rel" ]] || return 1
    if [[ "$rel" = /* ]]; then
        printf '%s\n' "$rel"
    else
        printf '%s/%s\n' "${SOURCE_PROJECT%/}" "$rel"
    fi
}

copy_required_file() {
    local source_path="$1"
    local target_path="$2"
    local mode="${3:-0644}"
    [[ -f "$source_path" ]] || die "Не найден обязательный файл: $source_path"
    install -D -m "$mode" "$source_path" "$target_path"
}

copy_optional_file() {
    local source_path="$1"
    local target_path="$2"
    local mode="${3:-0644}"
    [[ -f "$source_path" ]] || return 0
    install -D -m "$mode" "$source_path" "$target_path"
}

extract_engine_rel() {
    local core_path="$1"
    local engine_name
    engine_name="$(sed -n -E "s/^[[:space:]]*DEFAULT_ENGINE_FILE[[:space:]]*=.*[\"']([^\"']+)[\"'].*/\1/p" "$core_path" | sed -n '1p')"
    [[ -n "$engine_name" ]] || return 1
    if [[ "$engine_name" = /* ]]; then
        printf '%s\n' "$engine_name"
    elif [[ "$engine_name" == */* ]]; then
        printf '%s\n' "$engine_name"
    else
        printf 'host/%s\n' "$engine_name"
    fi
}

write_release_manifest() {
    local bundle_tmp="$1"
    local core_name="$2"
    local engine_name="$3"
    local gui_name="$4"
    local created_at="$5"
    local release="$bundle_tmp/project/host/bmi30_firmware_release.env"
    local core_rel="host/bmi30_active_runtime/project/host/$core_name"
    local engine_rel="host/bmi30_active_runtime/project/host/$engine_name"
    local gui_rel="host/bmi30_active_runtime/project/host/$gui_name"
    local portal_rel="host/bmi30_active_runtime/project/hotspot_info_server.py"

    {
        printf '# Auto-generated by create_bmi30_split_bundle.sh\n'
        printf 'BMI30_FIRMWARE_VERSION=%q\n' "$BUNDLE_ID"
        printf 'BMI30_FIRMWARE_LABEL=%q\n' "$BUNDLE_LABEL"
        printf 'BMI30_FIRMWARE_CREATED_AT=%q\n' "$created_at"
        printf 'BMI30_FIRMWARE_SIGNATURE_VERSION=9\n'
        printf 'BMI30_FIRMWARE_BUNDLE_ID=%q\n' "$BUNDLE_ID"
        printf 'BMI30_FIRMWARE_CORE_PATH=%q\n' "$core_rel"
        printf 'BMI30_FIRMWARE_CORE_SHA256=%q\n' "$(sha256sum "$bundle_tmp/project/host/$core_name" | awk '{print $1}')"
        printf 'BMI30_FIRMWARE_ENGINE_PATH=%q\n' "$engine_rel"
        printf 'BMI30_FIRMWARE_ENGINE_SHA256=%q\n' "$(sha256sum "$bundle_tmp/project/host/$engine_name" | awk '{print $1}')"
        printf 'BMI30_FIRMWARE_GUI_PATH=%q\n' "$gui_rel"
        printf 'BMI30_FIRMWARE_GUI_SHA256=%q\n' "$(sha256sum "$bundle_tmp/project/host/$gui_name" | awk '{print $1}')"
        printf 'BMI30_FIRMWARE_PORTAL_PATH=%q\n' "$portal_rel"
        printf 'BMI30_FIRMWARE_PORTAL_SHA256=%q\n' "$(sha256sum "$bundle_tmp/project/hotspot_info_server.py" | awk '{print $1}')"
        printf 'BMI30_FIRMWARE_CONFIG_PATH=%q\n' 'host/bmi30_active_runtime/project/host/bmi30_config.json'
        printf 'BMI30_FIRMWARE_CONFIG_SHA256=%q\n' "$(sha256sum "$bundle_tmp/project/host/bmi30_config.json" | awk '{print $1}')"
        printf 'BMI30_FIRMWARE_TAG_FILTERS_PATH=%q\n' 'host/bmi30_active_runtime/project/host/tag_response_filters'
        printf 'BMI30_FIRMWARE_USB_STREAM_PATH=%q\n' 'host/bmi30_active_runtime/project/host/usb_vendor/usb_stream.py'
        printf 'BMI30_FIRMWARE_USB_STREAM_SHA256=%q\n' "$(sha256sum "$bundle_tmp/project/host/usb_vendor/usb_stream.py" | awk '{print $1}')"
    } > "$release"
}

main() {
    parse_args "$@"

    [[ -n "$BUNDLE_ID" ]] || die "Нужен --id"
    [[ "$BUNDLE_ID" =~ ^[A-Za-z0-9._-]+$ ]] || die "ID может содержать только A-Z, a-z, 0-9, точку, _ и -"
    [[ -d "$SOURCE_PROJECT" ]] || die "Каталог проекта не найден: $SOURCE_PROJECT"
    [[ -d "$SOURCE_SYSTEM_ROOT" ]] || die "Корень системы не найден: $SOURCE_SYSTEM_ROOT"
    BUNDLE_LABEL="${BUNDLE_LABEL:-$BUNDLE_ID}"

    local active_env="$SOURCE_PROJECT/host/bmi30_split_active_version.env"
    [[ -f "$active_env" ]] || die "Не найден active env: $active_env"

    unset BMI30_CORE_PATH BMI30_ENGINE_SOURCE BMI30_GUI_PATH BMI30_PORTAL_PATH
    # shellcheck source=/dev/null
    source "$active_env"

    local core_rel="${BMI30_CORE_PATH:-}"
    local gui_rel="${BMI30_GUI_PATH:-host/BMI30.GUI.001.py}"
    local portal_rel="${PORTAL_SOURCE:-${BMI30_PORTAL_PATH:-hotspot_info_server.py}}"
    local core_path gui_path portal_path engine_rel engine_path
    core_path="$(resolve_project_file "$core_rel")"
    gui_path="$(resolve_project_file "$gui_rel")"
    portal_path="$(resolve_project_file "$portal_rel")"
    [[ -f "$core_path" ]] || die "Активный core не найден: $core_path"

    engine_rel="${BMI30_ENGINE_SOURCE:-}"
    if [[ -z "$engine_rel" ]]; then
        engine_rel="$(extract_engine_rel "$core_path")" || die "Не удалось определить engine из $core_path"
    fi
    engine_path="$(resolve_project_file "$engine_rel")"

    local final_dir="$BUNDLES_DIR/$BUNDLE_ID"
    [[ ! -e "$final_dir" ]] || die "Комплект уже существует и не будет перезаписан: $final_dir"

    mkdir -p "$BUNDLES_DIR"
    local tmp_dir="$BUNDLES_DIR/.${BUNDLE_ID}.tmp.$$"
    rm -rf -- "$tmp_dir"
    mkdir -p "$tmp_dir/project/host" "$tmp_dir/system" "$tmp_dir/metadata"
    trap 'rm -rf -- "${tmp_dir:-}"' EXIT

    local core_name engine_name gui_name created_at engine_dir
    core_name="$(basename -- "$core_path")"
    engine_name="$(basename -- "$engine_path")"
    gui_name="$(basename -- "$gui_path")"
    created_at="$(date -u +%Y-%m-%dT%H:%M:%SZ)"
    engine_dir="$(dirname -- "$engine_path")"

    copy_required_file "$core_path" "$tmp_dir/project/host/$core_name"
    copy_required_file "$engine_path" "$tmp_dir/project/host/$engine_name"
    copy_required_file "$gui_path" "$tmp_dir/project/host/$gui_name"
    copy_required_file "$portal_path" "$tmp_dir/project/hotspot_info_server.py" 0755

    local project_config="$engine_dir/bmi30_config.json"
    [[ -f "$project_config" ]] || project_config="$SOURCE_PROJECT/host/bmi30_config.json"
    copy_required_file "$project_config" "$tmp_dir/project/host/bmi30_config.json"
    copy_optional_file "$engine_dir/bmi30_sel.json" "$tmp_dir/project/host/bmi30_sel.json"
    copy_optional_file "$engine_dir/dc_offset_samples.npz" "$tmp_dir/project/host/dc_offset_samples.npz"
    copy_optional_file "$engine_dir/dc_offset_samples.npz.bak" "$tmp_dir/project/host/dc_offset_samples.npz.bak"
    copy_optional_file "$engine_dir/bmi30_runtime_support.py" "$tmp_dir/project/host/bmi30_runtime_support.py"
    copy_optional_file "$engine_dir/USB_config.json" "$tmp_dir/project/host/USB_config.json"
    copy_optional_file "$engine_dir/plot_config.json" "$tmp_dir/project/host/plot_config.json"

    local tag_filters_dir="$engine_dir/tag_response_filters"
    [[ -d "$tag_filters_dir" ]] || tag_filters_dir="$SOURCE_PROJECT/host/tag_response_filters"
    [[ -d "$tag_filters_dir" ]] || die "Не найдена обязательная папка tag_response_filters"
    rsync -a --exclude='__pycache__/' --exclude='*.pyc' \
        "$tag_filters_dir/" "$tmp_dir/project/host/tag_response_filters/"
    find "$tmp_dir/project/host/tag_response_filters" -maxdepth 1 -type f -name '*.json' -print -quit \
        | grep -q . || die "В комплект не попали JSON-файлы tag response filters"

    [[ -d "$engine_dir/usb_vendor" ]] || die "Не найден обязательный usb_vendor: $engine_dir/usb_vendor"
    rsync -a --exclude='__pycache__/' --exclude='*.pyc' \
        "$engine_dir/usb_vendor/" "$tmp_dir/project/host/usb_vendor/"
    [[ -f "$tmp_dir/project/host/usb_vendor/usb_stream.py" ]] || die "В комплект не попал usb_stream.py"

    if (( INCLUDE_PLAYER == 1 )) && [[ -d "$engine_dir/player_recordings" ]]; then
        rsync -a --exclude='__pycache__/' --exclude='*.pyc' \
            "$engine_dir/player_recordings/" "$tmp_dir/project/host/player_recordings/"
    fi

    local system_prefix="${SOURCE_SYSTEM_ROOT%/}"
    [[ -n "$system_prefix" ]] || system_prefix=""
    copy_optional_file "$system_prefix/etc/bmi30/portal_config.json" \
        "$tmp_dir/system/etc/bmi30/portal_config.json" 0640
    copy_optional_file "$system_prefix/usr/local/bin/host/bmi30_config.json" \
        "$tmp_dir/system/usr/local/bin/host/bmi30_config.json"
    copy_required_file "$active_env" "$tmp_dir/metadata/source_active_version.env"

    write_release_manifest "$tmp_dir" "$core_name" "$engine_name" "$gui_name" "$created_at"

    {
        printf '# Complete BMI30 websplit bundle manifest\n'
        printf 'BMI30_BUNDLE_FORMAT=1\n'
        printf 'BMI30_BUNDLE_HARDWARE_PWM=1\n'
        printf 'BMI30_BUNDLE_ID=%q\n' "$BUNDLE_ID"
        printf 'BMI30_BUNDLE_LABEL=%q\n' "$BUNDLE_LABEL"
        printf 'BMI30_BUNDLE_ORIGIN=%q\n' "$BUNDLE_ORIGIN"
        printf 'BMI30_BUNDLE_CREATED_AT=%q\n' "$created_at"
        printf 'BMI30_BUNDLE_SOURCE_CORE_PATH=%q\n' "$core_rel"
        printf 'BMI30_BUNDLE_SOURCE_ENGINE_PATH=%q\n' "$engine_rel"
        printf 'BMI30_BUNDLE_CORE_REL=%q\n' "project/host/$core_name"
        printf 'BMI30_BUNDLE_ENGINE_REL=%q\n' "project/host/$engine_name"
        printf 'BMI30_BUNDLE_GUI_REL=%q\n' "project/host/$gui_name"
        printf 'BMI30_BUNDLE_PORTAL_REL=%q\n' 'project/hotspot_info_server.py'
        printf 'BMI30_BUNDLE_PROJECT_CONFIG_REL=%q\n' 'project/host/bmi30_config.json'
        printf 'BMI30_BUNDLE_SYSTEM_CONFIG_REL=%q\n' 'system/etc/bmi30/portal_config.json'
        printf 'BMI30_BUNDLE_INSTALLED_CONFIG_REL=%q\n' 'system/usr/local/bin/host/bmi30_config.json'
        printf 'BMI30_BUNDLE_TAG_FILTERS_REL=%q\n' 'project/host/tag_response_filters'
        printf 'BMI30_BUNDLE_USB_VENDOR_REL=%q\n' 'project/host/usb_vendor'
        printf 'BMI30_BUNDLE_PLAYER_REL=%q\n' 'project/host/player_recordings'
        printf 'BMI30_BUNDLE_RELEASE_REL=%q\n' 'project/host/bmi30_firmware_release.env'
    } > "$tmp_dir/manifest.env"

    (
        cd "$tmp_dir"
        find manifest.env project system metadata -type f -print0 \
            | sort -z \
            | xargs -0 sha256sum > SHA256SUMS
        sha256sum -c SHA256SUMS >/dev/null
    )

    mv -- "$tmp_dir" "$final_dir"
    trap - EXIT

    local owner_user owner_group
    owner_user="${SUDO_USER:-$(id -un)}"
    owner_group="$(id -gn "$owner_user" 2>/dev/null || printf '%s' "$owner_user")"
    if [[ $(id -u) -eq 0 ]]; then
        chown -R "$owner_user:$owner_group" "$final_dir"
    fi

    info "Создан полный BMI30-комплект: $final_dir"
    info "Core: $core_name"
    info "Engine: $engine_name"
    info "GUI/portal/config/usb_vendor/player сохранены вместе с версией"
}

main "$@"
